# Generated by Django 5.0.6 on 2024-05-31 11:35

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('experience', models.IntegerField()),
                ('compony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.compony')),
            ],
        ),
    ]
