# Generated by Django 5.0.6 on 2024-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_district_alter_vacancy_compony_vacancy_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='work_time',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('project_work', 'Project Time')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
